services:
  server:
    container_name: server
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    expose:
      - 5174
    ports:
      - "5174:5174"
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5174"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    command: yarn run deploy
    

  postgres: 
    image: "postgres:16.1-bullseye"
    container_name: postgres
    user:
      postgres
    restart: always
    hostname: postgres
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - "3000:5432"
    healthcheck:
      test: [ "CMD", "service_started"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:

volumes:
  db-data: